{% set name = "enso_metrics" %}
{% set version = "1.1.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/CLIVAR-PRP/ENSO_metrics/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b42e9530bcdaed8f85021f9147624639620e5eaae78c39ec214d473b68954954    

build:
  number: 1
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cdms2
    - cdutil
    - genutil
    - numpy
    - scipy
    - udunits2

test:
  imports:
    - EnsoMetrics.EnsoCollectionsLib
    - EnsoMetrics.EnsoComputeMetricsLib
  commands:
    - pip check
  requires:
    - pip

about:
    home: https://github.com/CLIVAR-PRP/ENSO_metrics
    license: BSD-3-Clause
    license_file: LICENSE
    summary: "Library to compute ENSO metrics"

extra:
  recipe-maintainers:
    - eguil
    - lee1043
    - acordonez
    - yyplanton
