{% set name = "enso_metrics" %}
{% set version = "1.1.5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/CLIVAR-PRP/ENSO_metrics/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 29fe3f195b48c5ca953d81a17a3ae16c1a6ceed13f345d2d56635882fb9db0c2    

build:
  number: 0
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cartopy
    - cdms2
    - cdutil
    - genutil
    - numpy
    - scipy
    - udunits2
    - packaging

test:
  imports:
    - EnsoMetrics.EnsoCollectionsLib
    - EnsoMetrics.EnsoComputeMetricsLib
  commands:
    - pip check
  requires:
    - pip

about:
    home: https://github.com/CLIVAR-PRP/ENSO_metrics
    license: BSD-3-Clause
    license_file: LICENSE
    summary: "Library to compute ENSO metrics"

extra:
  recipe-maintainers:
    - eguil
    - lee1043
    - acordonez
    - yyplanton
